config/routes.rb
Rails.application.routes.draw do
  root to: 'orders#index'

  resources :orders, only: %i[index show create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates_presence_of :name
end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :quantity

  belongs_to :order
  belongs_to :product
  belongs_to :supplier
  belongs_to :customer
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :items

  # Total value order
  def total
    items.includes(:product).sum('price * quantity')
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :description
  validates_presence_of :price
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  # GET /orders or /orders.json
  def index
    @orders = Order.all.order(id: :desc)
  end

  # GET /orders/1 or /orders/1.json
  def show
    @order = Order.includes(:items).find(params[:id])
  end

  def create
    order_file = params[:file]
    result = ParseOrderFile.call(file: order_file, locale: :pt)
    @order = result.order 
    respond_to do |format|
      format.html { redirect_to action: :index }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orders Management | Dev9NamaTest</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

  </head>

  <body>
    <div class="mx-auto max-w-sm lg:max-w-4xl">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_dropzone.html.erb
<section class="h-full overflow-auto p-8 w-full h-full flex flex-col">
    <header class="border-dashed border-2 border-gray-400 py-12 flex flex-col justify-center items-center">
      <%= form_with url: orders_path(format: :html), remote: true, local: false, class: "dropzone mt-2 rounded-sm px-3 py-1 bg-gray-200 hover:bg-gray-300 focus:shadow-outline focus:outline-none", id: "my-awesome-dropzone" do |form| %>
      <% end %>
    </header>
</section>

<script>  
  Dropzone.options.myAwesomeDropzone = {
    paramName: "file",
    dictDefaultMessage: "Click or drag to upload files",
    dictFileTooBig: "Very large file. Limit: 20mb",
    maxFilesize: 20, // MB
    success: function(data, response) {
      toastr.success('Uploaded with success!')
    }
  };
</script>

app/views/orders/index.html.erb
<h1 class="text-center text-5xl font-semibold text-blue-500">Orders Management</h1>

<%= render "dropzone" %>

<div class="-my-2 py-2 overflow-x-auto">             
  <div class="align-middle inline-block min-w-full shadow overflow-hidden bg-white shadow-dashboard px-8 pt-3 rounded-bl-lg rounded-br-lg">
    <table class="min-w-full">
      <thead>
        <tr>
          <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Order</th>
          <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Date</th>
          <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Amount</th>
          <th class="px-6 py-3 border-b-2 border-gray-300"></th>
        </tr>
      </thead>
      <tbody class="bg-white">
        <% @orders.each do |order| %>
          <tr>
            <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500">
              <div class="text-sm leading-5 text-blue-900">Order #<%= order.id %></div>
            </td>
            <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5">
              <%= order.created_at.strftime('%m/%d/%Y') %>
            </td>
            <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5">
              <%= number_to_currency(order.total, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
            </td>
            <td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-500 text-sm leading-5">
              <%= link_to "View", order_path(order), class: "px-5 py-2 border-blue-500 border text-blue-500 rounded transition duration-300 hover:bg-blue-700 hover:text-white focus:outline-none" %>
            </td>
          </tr>
        <% end %>

        <% if @orders.empty? %>
          <tr class="text-center">
            <td></td>
            <td>No files uploaded.</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/show.html.erb
<h1 class="text-center text-5xl font-semibold text-blue-500">Pedido #<%= @order.id %></h1>

<div class="align-middle inline-block min-w-full shadow overflow-hidden bg-white shadow-dashboard px-8 pt-3 rounded-bl-lg rounded-br-lg">
  <table class="min-w-full text-center table-auto">
      <thead>
          <tr>
              <th>Customer</th>
              <th>Description</th>
              <th>Price</th>
              <th>Quantity</th>
              <th>Address</th>
              <th>Supplier</th>
          <tr>
      <thead>
    <tbody>
      <% @order.items.each do |item| %>
        <tr>
          <td><%= item.customer.name %></td>
          <td><%= item.product.description %></td>
          <td><%= number_to_currency(item.product.price, :unit => "R$ ", :separator => ",", :delimiter => ".") %></td>
          <td><%= item.quantity %></td>
          <td><%= item.supplier.address %></td>
          <td><%= item.supplier.name %></td>
        </tr>
      <% end %>
        <tr>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td><strong>Total: </strong></td>
          <td class="text-red-500 font-semibold text-2xl">
            <%= number_to_currency(@order.total, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
          </td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
    </tbody>
  </table>
</div>

<%= link_to "Voltar", orders_path, class: "border border-indigo-500 bg-indigo-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-indigo-600 focus:outline-none focus:shadow-outline flex flex-col justify-center items-center" %>